development:
  adapter: mysql
  database: textbuster-dev
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  password: 

test:
  adapter: mysql
  database: textbuster-test
  username: root
  password: 
  pool: 5
  timeout: 5000
  host: 127.0.0.1

production:
  adapter: mysql
  database: textbuster
  username: textbuster
  password: mz-db-123
  pool: 5
  timeout: 5000
  host: localhost

